export const genres = [
  "African Regional Genres",
  "Ambient",
  "Asian & Middle Eastern Regional Genres",
  "Audiobooks & Spoken Word",
  "Blues",
  "Classical",
  "Country",
  "Dance/Electronic",
  "European Regional Genres",
  "Folk",
  "Hip-Hop",
  "Indie",
  "Inspirational",
  "Jazz",
  "Latin American Regional Genres",
  "Metal",
  "North American Regional Genres",
  "Pop",
  "Punk",
  "R&B/Soul",
  "Reggae",
  "Rock",
  "Sounds & Non-music",
];
